name: comfort_route_sample
description: Comfort-first route planning APK sample.
publish_to: 'none'
version: 0.6.7+14

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.3.1
  geolocator: ^14.0.3
  geolocator_android: ^5.0.3
  latlong2: ^0.10.1
  maplibre_gl: ^0.26.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
